# XXX: Precise is already deprecated, new default is Trusty.
# https://blog.travis-ci.com/2017-07-11-trusty-as-default-linux-is-coming
dist: precise
sudo: true
language: c

jobs:
  include:
    - &test-ubuntu
      stage: test
      compiler: gcc
      addons:
        apt:
          packages:
            - gfortran
      before_script: &common-before
        - COMMON_FLAGS="DYNAMIC_ARCH=1 TARGET=NEHALEM NUM_THREADS=32"
      script:
        - set -e
        - travis_wait 45 make QUIET_MAKE=1 $COMMON_FLAGS $BTYPE
        - make -C test $COMMON_FLAGS $BTYPE
        - make -C ctest $COMMON_FLAGS $BTYPE
        - make -C utest $COMMON_FLAGS $BTYPE
      env:
        - TARGET_BOX=LINUX64
        - BTYPE="BINARY=64"

    - <<: *test-ubuntu
      env:
        - TARGET_BOX=LINUX64
        - BTYPE="BINARY=64 USE_OPENMP=1"

    - <<: *test-ubuntu
      env:
        - TARGET_BOX=LINUX64
        - BTYPE="BINARY=64 INTERFACE64=1"

    - <<: *test-ubuntu
      compiler: clang
      env:
        - TARGET_BOX=LINUX64
        - BTYPE="BINARY=64 CC=clang"

    - <<: *test-ubuntu
      compiler: clang
      env:
        - TARGET_BOX=LINUX64
        - BTYPE="BINARY=64 INTERFACE64=1 CC=clang"

    - <<: *test-ubuntu
      addons:
        apt:
          packages:
            - gcc-multilib
            - gfortran-multilib
      env:
        - TARGET_BOX=LINUX32
        - BTYPE="BINARY=32"

    - stage: test
      compiler: gcc
      addons:
        apt:
          packages:
            - binutils-mingw-w64-x86-64
            - gcc-mingw-w64-x86-64
            - gfortran-mingw-w64-x86-64
      before_script: *common-before
      script:
        - travis_wait 45 make QUIET_MAKE=1 $COMMON_FLAGS $BTYPE
      env:
        - TARGET_BOX=WIN64
        - BTYPE="BINARY=64 HOSTCC=gcc CC=x86_64-w64-mingw32-gcc FC=x86_64-w64-mingw32-gfortran"

    - &test-cmake
      stage: test
      compiler: clang
      addons:
        apt:
          packages:
            - gfortran
            - cmake
      dist: trusty
      sudo: true
      before_script:
        - COMMON_ARGS="-DTARGET=NEHALEM -DNUM_THREADS=32"
      script:
        - set -e
        - mkdir build
        - CONFIG=Release
        - cmake -Bbuild -H. $CMAKE_ARGS $COMMON_ARGS -DCMAKE_BUILD_TYPE=$CONFIG
        - cmake --build build --config $CONFIG -- -j2
      env:
        - CMAKE=1
    - <<: *test-cmake
      env:
        - CMAKE=1 CMAKE_ARGS="-DNOFORTRAN=1"
    - <<: *test-cmake
      compiler: gcc
      env:
        - CMAKE=1

# whitelist
branches:
  only:
    - master
    - develop

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/8a6e4470a0cebd090344
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
